types = [
    "Normal",
    "Fire",
    "Water",
    "Electric",
    "Grass",
    "Ice",
    "Fighting",
    "Poison",
    "Ground",
    "Flying",
    "Psychic",
    "Bug",
    "Rock",
    "Ghost",
    "Dragon",
    "Dark",
    "Steel",
    "Fairy",
    "Stellar",
]

items = [
    "Zoom Lens",
    "Zap Plate",
    "Yellow Nectar",
    "Wise Glasses",
    "Wide Lens",
    "White Herb",
    "Weakness Policy",
    "Wave Incense",
    "Waterium Z",
    "Water Memory",
    "Water Gem",
    "Venusaurite",
    "Utility Umbrella",
    "Ultranecrozium Z",
    "Tyranitarite",
    "Twisted Spoon",
    "Toxic Plate",
    "Toxic Orb",
    "Throat Spray",
    "Thick Club",
    "Terrain Extender",
    "Tart Apple",
    "Tapunium Z",
    "Syrupy Apple",
    "Sweet Apple",
    "Swampertite",
    "Strawberry Sweet",
    "Stone Plate",
    "Sticky Barb",
    "Steelixite",
    "Steelium Z",
    "Steel Memory",
    "Steel Gem",
    "Star Sweet",
    "Spooky Plate",
    "Splash Plate",
    "Spell Tag",
    "Soul Dew",
    "Soothe Bell",
    "Solganium Z",
    "Soft Sand",
    "Snowball",
    "Snorlium Z",
    "Smooth Rock",
    "Smoke Ball",
    "Slowbronite",
    "Sky Plate",
    "Silver Powder",
    "Silk Scarf",
    "Shock Drive",
    "Shell Bell",
    "Shed Shell",
    "Sharpedonite",
    "Sharp Beak",
    "Sea Incense",
    "Scope Lens",
    "Scizorite",
    "Sceptilite",
    "Salamencite",
    "Safety Goggles",
    "Sablenite",
    "Rose Incense",
    "Room Service",
    "Rocky Helmet",
    "Rockium Z",
    "Rock Memory",
    "Rock Incense",
    "Rock Gem",
    "Ring Target",
    "Ribbon Sweet",
    "Red Nectar",
    "Red Card",
    "Razor Fang",
    "Razor Claw",
    "Quick Powder",
    "Quick Claw",
    "Purple Nectar",
    "Pure Incense",
    "Psychium Z",
    "Psychic Seed",
    "Psychic Memory",
    "Psychic Gem",
    "Protective Pads",
    "Prof's Letter",
    "Prison Bottle",
    "Primarium Z",
    "Power Weight",
    "Power Plant Pass",
    "Power Lens",
    "Power Herb",
    "Power Bracer",
    "Power Belt",
    "Power Band",
    "Power Anklet",
    "Poisonium Z",
    "Poison Memory",
    "Poison Gem",
    "Poison Barb",
    "Plasma Card",
    "Pixie Plate",
    "Pinsirite",
    "Pink Nectar",
    "Pikashunium Z",
    "Pikanium Z",
    "Pidgeotite",
    "Pass Orb",
    "Odd Incense",
    "Normalium Z",
    "Normal Gem",
    "Never-Melt Ice",
    "Mystic Water",
    "Muscle Band",
    "Misty Seed",
    "Mirror Herb",
    "Miracle Seed",
    "Mind Plate",
    "Mimikium Z",
    "Mewtwonite Y",
    "Mewtwonite X",
    "Mewnium Z",
    "Metronome",
    "Metal Powder",
    "Metal Coat",
    "Metagrossite",
    "Mental Herb",
    "Medichamite",
    "Meadow Plate",
    "Mawilite",
    "Marshadium Z",
    "Manectite",
    "Magnet",
    "Macho Brace",
    "Lycanium Z",
    "Lustrous Orb",
    "Lustrous Globe",
    "Lunalium Z",
    "Luminous Moss",
    "Lucky Punch",
    "Lucky Egg",
    "Luck Incense",
    "Lucarionite",
    "Love Sweet",
    "Lopunnite",
    "Looker Ticket",
    "Loaded Dice",
    "Light Clay",
    "Light Ball",
    "Life Orb",
    "Legend Plate",
    "Leftovers",
    "Leek",
    "Lax Incense",
    "Latiosite",
    "Latiasite",
    "Lagging Tail",
    "Kommonium Z",
    "King's Rock",
    "Kangaskhanite",
    "Iron Plate",
    "Iron Ball",
    "Intriguing Stone",
    "Insect Plate",
    "Incinium Z",
    "Icy Rock",
    "Icium Z",
    "Icicle Plate",
    "Ice Memory",
    "Ice Gem",
    "Houndoominite",
    "Honor Of Kalos",
    "Hi-tech Earbuds",
    "Heracronite",
    "Heavy-Duty Boots",
    "Heat Rock",
    "Hard Stone",
    "Gyaradosite",
    "Grubby Hanky",
    "Groundium Z",
    "Ground Memory",
    "Ground Gem",
    "Grit Rock",
    "Grit Pebble",
    "Grit Gravel",
    "Grit Dust",
    "Griseous Orb",
    "Griseous Core",
    "Grip Claw",
    "Grassy Seed",
    "Grassium Z",
    "Grass Memory",
    "Grass Gem",
    "Glalitite",
    "Ghostium Z",
    "Ghost Memory",
    "Ghost Gem",
    "Gengarite",
    "Gardevoirite",
    "Garchompite",
    "Galladite",
    "Full Incense",
    "Focus Sash",
    "Focus Band",
    "Flyinium Z",
    "Flying Memory",
    "Flying Gem",
    "Flower Sweet",
    "Float Stone",
    "Flame Plate",
    "Flame Orb",
    "Fist Plate",
    "Firium Z",
    "Fire Memory",
    "Fire Gem",
    "Fightinium Z",
    "Fighting Memory",
    "Fighting Gem",
    "Fairy Memory",
    "Fairium Z",
    "Expert Belt",
    "Exp. Share",
    "Eviolite",
    "Everstone",
    "Elevator Key",
    "Electrium Z",
    "Electric Seed",
    "Electric Memory",
    "Electric Gem",
    "Eject Pack",
    "Eject Button",
    "Eevium Z",
    "Earth Plate",
    "Dropped Item",
    "Dread Plate",
    "Dragonium Z",
    "Dragon Memory",
    "Dragon Gem",
    "Dragon Fang",
    "Draco Plate",
    "Douse Drive",
    "Diancite",
    "Destiny Knot",
    "Deep Sea Tooth",
    "Deep Sea Scale",
    "Decidium Z",
    "Darkinium Z",
    "Dark Memory",
    "Dark Gem",
    "Damp Rock",
    "Cracked Pot",
    "Covert Cloak",
    "Clover Sweet",
    "Cleanse Tag",
    "Choice Specs",
    "Choice Scarf",
    "Choice Band",
    "Chipped Pot",
    "Chill Drive",
    "Charizardite Y",
    "Charizardite X",
    "Charcoal",
    "Cell Battery",
    "Cameruptite",
    "Burn Drive",
    "Buginium Z",
    "Bug Memory",
    "Bug Gem",
    "Bright Powder",
    "Blunder Policy",
    "Blazikenite",
    "Blastoisinite",
    "Blank Plate",
    "Black Sludge",
    "Black Glasses",
    "Black Belt",
    "Binding Band",
    "Big Root",
    "Berry Sweet",
    "Beedrillite",
    "Banettite",
    "Audinite",
    "Assault Vest",
    "Amulet Coin",
    "Ampharosite",
    "Altarianite",
    "Aloraichium Z",
    "Alakazite",
    "Air Balloon",
    "Aggronite",
    "Aerodactylite",
    "Adrenaline Orb",
    "Adamant Orb",
    "Adamant Crystal",
    "Occa Berry",
    "Passho Berry",
    "Wacan Berry",
    "Rindo Berry",
    "Yache Berry",
    "Chople Berry",
    "Kebia Berry",
    "Shuca Berry",
    "Coba Berry",
    "Payapa Berry",
    "Tanga Berry",
    "Charti Berry",
    "Kasib Berry",
    "Haban Berry",
    "Colbur Berry",
    "Babiri Berry",
    "Chilan Berry"
]
